AppBundle\Entity\User:
  type: entity
  table: code_care_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      unique: true
      length: 25
    password:
      type: string
      length: 64
    isActive:
      type: boolean
      nullable: true
      column: is_active
